#! /usr/bin/sh

# Spaces
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8
bspc monitor DP-1 -d 9
bspc monitor DP-2 -d 0

# Border
bspc config border_width          0
# bspc config normal_border_color   "#262626"
# bspc config focused_border_color  "#d75fd7"
# bspc config urgent_border_color   "#B58900"
# bspc config presel_border_color   "#26E2FF"

# Split
bspc config window_gap            0 # default 12
bspc config split_ratio           0.50

# Monocle
bspc config borderless_monocle    true
bspc config gapless_monocle       true

# Focus
bspc config focus_follows_pointer false
bspc config history_aware_focus   true
bspc config focus_by_distance     true

# Rules
bspc rule -a URxvt:dropdown sticky=on state=floating hidden=on
urxvt +tr -name dropdown -e $HOME/bin/dropdown.sh &

# External rules command
# bspc config external_rules_command $HOME/.config/bspwm/external-rules.sh
